config/routes.rb
Rails.application.routes.draw do
  
  get 'followers/index'
  get 'following/index'
  get 'home/show'
  get 'home/index'
  get 'tweets/new'
  get 'tweets/create'
  get 'welcome/index'

   root 'home#index'

  
	get 'auth/:provider/callback', to: 'sessions#create'
	get 'auth/failure', to: redirect('/')
	get 'signout', to: 'sessions#destroy', as: 'signout'
	  resources :tweets, only: [:new, :create]
	  resources :sessions, only: [:create, :destroy]
	  resource :home, only: [:show]
	  
	get '/auth/failure', :to => 'sessions#failure'
	get '/logout', :to => 'sessions#destroy'
	

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user
	validates :provider, :uid, :presence => true
	
end

app/models/tweets.rb
class Tweets < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_secret = auth.credentials.secret
      user.save!
    end
  end

  def tweet(tweet)
		client = Twitter::REST::Client.new do |config|
		  config.consumer_key        = "NCj4dwSFDYMnamQeNFHpV0jWg"
		  config.consumer_secret     = "bwMvMxZNnp4RD9d5ACxY0jj4bj5TuoMoMQorZm75RuDQOPGdsW"
		  config.access_token        = oauth_token
		  config.access_token_secret = oauth_secret
		end
		client.update(tweet)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
	unless(current_user.nil?)
	
		 client = Twitter::REST::Client.new do |config|
		  config.consumer_key        = "NCj4dwSFDYMnamQeNFHpV0jWg"
		  config.consumer_secret     = "bwMvMxZNnp4RD9d5ACxY0jj4bj5TuoMoMQorZm75RuDQOPGdsW"
		  config.access_token        = current_user.oauth_token
		  config.access_token_secret = current_user.oauth_secret
		end
		@followers = client.followers()
	  end
  end

end

app/controllers/following_controller.rb
class FollowingController < ApplicationController
  def index
  unless(current_user.nil?)
	
      client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "NCj4dwSFDYMnamQeNFHpV0jWg"
      config.consumer_secret     = "bwMvMxZNnp4RD9d5ACxY0jj4bj5TuoMoMQorZm75RuDQOPGdsW"
      config.access_token        = current_user.oauth_token
      config.access_token_secret = current_user.oauth_secret
    end
	@friends = client.friends()
  end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
	unless(current_user.nil?)
	  client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "NCj4dwSFDYMnamQeNFHpV0jWg"
      config.consumer_secret     = "bwMvMxZNnp4RD9d5ACxY0jj4bj5TuoMoMQorZm75RuDQOPGdsW"
      config.access_token        = current_user.oauth_token
      config.access_token_secret = current_user.oauth_secret
    end
		@tweets = client.user_timeline(count: 3200 )
		
		#TweetsController.tweets_store(@tweets)
		
		@followers = client.followers()
		@friends = client.friends()
	end
  end

  def show
  
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
  end

  def create
    current_user.tweet(twitter_params[:message])
  end

  def twitter_params
    params.require(:tweet).permit(:message)
  end
  
  def self.tweets_store(tweets)
	 tweets.each do |tweet|
		if Tweets.where(:tweet_id => tweet.id).blank?
			new_tweet = Tweets.new
			new_tweet.tweet_id = tweet.id
			new_tweet.tweet_text = tweet.text
			new_tweet.created_at = tweet.created_at
			new_tweet.retweets = tweet.retweet_count
			new_tweet.favorite_count = tweet.favorite_count
			new_tweet.save
		end
	 end
  
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/followers/_index.html.erb
  <% if !current_user.nil? %>
  <% @followers.each do |follower| %>
		 <%= link_to "@#{follower.screen_name}", "http://www.twitter.com/#{follower.screen_name}" %>
		 <br>
  <% end %>
    <% end %>

app/views/followers/index.html.erb
  <% if !current_user.nil? %>
  <% @followers.each do |follower| %>
		 <%= link_to "@#{follower.screen_name}", "http://www.twitter.com/#{follower.screen_name}" %>
		 <br>
  <% end %>
    <% end %>

app/views/following/index.html.erb
  <% if !current_user.nil? %>
  <% @friends.each do |friend| %>
		 <%= link_to "@#{friend.screen_name}", "http://www.twitter.com/#{friend.screen_name}" %>
		 <br>
  <% end %>


  <% end %>

app/views/home/index.html.erb
<% if !current_user.nil? %>

  
<div class="container">
    <div class="row row-centered">
  <div class="col-xs-6 col-sm-2"> <h4>Following</h4> <% @friends.each do |friend| %>
		 <%= link_to "@#{friend.screen_name}", "http://www.twitter.com/#{friend.screen_name}" %>
		 <br>
  <% end %></div>
  
 
  <div class="col-xs-6 col-sm-8">
	<h4> My Tweets!</h4>
		<% @tweets.each do |tweet| %>
			<div class="panel panel-default">
				<div class="panel-heading"><%= tweet.text %></div>
				<div class="panel-body">
					 Retweets: <%= tweet.retweet_count %> <br>
					 Mentions:<%  tweet.user_mentions.each do |user_mention| %> 
						<%= link_to "@#{user_mention.screen_name} ", "https://twitter/#{user_mention.screen_name}" %>
					 <% end %> <br> 
					 Hashtags: <%  tweet.hashtags.each do |hashtag| %> 
						<%= link_to "##{hashtag.text} ", "https://twitter.com/hashtag/#{hashtag.text}?src=hash" %>
					 <% end %> <br>
					 Tweeted On: <%= tweet.created_at %><br>
					 <%= link_to "View Tweet on Twitter!","#{tweet.url}" %>
				</div>
			</div>
	  <% end %> 
	  
</div>
  <div class="col-xs-6 col-sm-2"> <h4>Followers</h4>
  
		<% @followers.count.to_s %>
		<% @followers.each do |follower| %>
		  <%= link_to "@#{follower.screen_name}", "http://www.twitter.com/#{follower.screen_name}" %>
		 <br>
  <% end %></div>
    </div>
<% else %>
    <p>This application requires an account with <%= link_to "Twitter","www.twitter.com" %></p>
	 <p>When logged in it will display list of tweets made by your <%= link_to "Twitter","www.twitter.com" %> account and some information about them.</p>
	 <p><%= link_to "Twitter","www.twitter.com" %> has put limitation on the number of calls it can make to its website. Too many calls can make this application no longer work for up to 15 minutes.</p>
	 <p>The source code for this project is located here on <%= link_to "https://bitbucket.org/jbridenthal/twitter-application", "https://bitbucket.org/jbridenthal/twitter-application" %></p>
	 
<% end %>
<div>

app/views/home/show.html.erb
<% if !current_user.nil? %>
    <p>Click The link below to send a tweet.</p>
    <%= link_to "Send a Tweet", new_tweet_path %>
<% else %>
    <p>You must log in to send a tweet.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  <title>Twitterapplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
   <ul class="nav nav-pills">
    <li class="drowpdown">  <%= link_to "Home", home_index_path %></li>
	<% if current_user %>
		<li class="drowpdown">  <%= link_to "Send a Tweet!", new_tweet_path %></li>
	<% end %>
	<li class="drowpdown pull-right">
		<% if current_user %>
			<%= link_to "Welcome #{current_user.name }, Sign Out", signout_path %>
		<% else %>
			<%= link_to "Sign in with Twitter", "/auth/twitter" %>
		<% end %></li>
    </ul>
	<hr>
	<div>
<%= yield %></div>
   



</body>
</html>

app/views/tweets/create.html.erb
<h1>Success!</h1>
<p>Your tweet has been sent!</p>
<%= link_to "Would you like to send another?", new_tweet_path %>

app/views/tweets/new.html.erb
<script>

function countChar(val) {

    var len = val.value.length;

    var str = val.value;
    var partSize = 140;

    while (str) {
            var rtext = (partSize - str.length) + " Chars Remaining";
			
            break;
    }
    $('#text-remaining').val(rtext);
	if(partSize < str.length) {
			document.getElementById("text-remaining").style.color = "red";
		}
}

function validateForm() {
    var x = document.forms["TweetForm"]["tweet[message]"].value;
    if (x==null || x=="") {
        window.alert("No message was entered!");
        return false;
    }
	if (x.length > 140) {
		window.alert("Tweets cannot be over 140 characters!");
        return false;
	}
	
}
</script>
<p>
  <%= form_for :tweet,url: tweets_path,  method: :post, html: { name: "TweetForm",onsubmit: "return validateForm()" } do |f| %>
    <%= f.text_area :message, cols: 70, onkeyup: "countChar(this)"%><br>
    <%= f.submit "Send Tweet" %>
<input id="text-remaining" class="input-medium uneditable-input" style="border: none" placeholder="140 Chars Remaining" readonly /> 
  <% end %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>